"""Generate downloadable verification reports as plain-text files.

A production system would use a PDF library (e.g. reportlab or weasyprint).
For this prototype we generate a structured text report that can be saved
and printed.
"""

from datetime import datetime
import json

from app.models.verification import VerificationRequest


def generate_verification_report(request: VerificationRequest) -> str:
    """Generate a text-based verification report for a completed request."""
    employer = request.employer
    lines = [
        "=" * 60,
        "SA VERIFY - VERIFICATION REPORT",
        "=" * 60,
        "",
        f"Report generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        f"Request ID: {request.id}",
        f"Status: {request.status.upper()}",
        "",
        "--- EMPLOYER ---",
        f"Name: {employer.full_name if employer else 'N/A'}",
        f"Reason: {request.reason or 'Not specified'}",
        "",
        "--- CANDIDATE ---",
        f"ID Number: {_mask_id(request.candidate_id_number)}",
        "",
        f"Submitted: {request.created_at.strftime('%Y-%m-%d %H:%M') if request.created_at else 'N/A'}",
        f"Last updated: {request.updated_at.strftime('%Y-%m-%d %H:%M') if request.updated_at else 'N/A'}",
        "",
        "--- QUERY RESULTS ---",
        "",
    ]

    for i, item in enumerate(request.items, 1):
        params = json.loads(item.query_params)
        lines.append(f"  {i}. {_query_label(item.query_type)}")
        lines.append(f"     Parameters: {_format_params(params)}")
        lines.append(f"     Consent: {item.consent_status.upper()}")

        if item.consent_status == "approved":
            lines.append(f"     Result: {item.result or 'N/A'}")
        elif item.consent_status == "declined":
            lines.append("     Result: CONSENT DECLINED")
        else:
            lines.append("     Result: PENDING")

        if item.responded_at:
            lines.append(f"     Responded: {item.responded_at.strftime('%Y-%m-%d %H:%M')}")
        lines.append("")

    lines.extend([
        "--- END OF REPORT ---",
        "",
        "This report was generated by SA Verify, the National Verification",
        "System prototype. Results are based on data held at the time of the",
        "query and are subject to the candidate's consent decisions.",
        "",
        "=" * 60,
    ])

    return "\n".join(lines)


def _mask_id(id_number: str) -> str:
    if not id_number or len(id_number) < 6:
        return id_number
    return id_number[:6] + "*" * (len(id_number) - 6)


def _query_label(query_type: str) -> str:
    labels = {
        "id_verification": "ID Verification",
        "employment_check": "Employment Check",
        "employment_period": "Employment Period",
        "salary_bracket": "Salary Bracket",
        "qualification_check": "Qualification Check",
        "criminal_record_check": "Criminal Record Check",
        "interpol_check": "Interpol / International Wanted Check",
        "credit_check": "Credit Check",
        "drivers_licence_check": "Driver's Licence Check",
        "professional_registration_check": "Professional Registration Check",
        "address_verification": "Address Verification",
        "reference_check": "Reference Check",
    }
    return labels.get(query_type, query_type)


def _format_params(params: dict) -> str:
    if not params:
        return "None"
    parts = [f"{k}={v}" for k, v in params.items()]
    return ", ".join(parts)
